account/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, {"template_name": "account/login.html", "redirect_authenticated_user": True}, name='login'),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='logout'),
]

article/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^list$', views.article_list, name='article_list'),
    url(r'^my/list$', views.my_article_list, name='my_article_list'),
    url(r'^(?P<id>\d+)/post/list$', views.article_post_list, name='article_post_list'),
    url(r'^create$', views.article_create, name='article_create'),
    url(r'^(?P<id>\d+)/comment$', views.article_comment, name='article_comment'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/comment$', views.article_post_comment, name='article_post_comment'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/edit$', views.article_edit, name='article_edit'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/reedit$', views.article_reedit, name='article_reedit'),
    url(r'^(?P<id>\d+)/body$', views.article_post_body, name='article_post_body'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/comment/list$', views.article_comment_list, name='article_comment_list'),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'project.views.handler400'
handler403 = 'project.views.handler403'
handler404 = 'project.views.handler404'
handler500 = 'project.views.handler500'

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.urlresolvers import reverse

class Article(models.Model):
    author    = models.ForeignKey(User, related_name='article')
    reviewers = models.ManyToManyField(User, related_name='review_articles')
    title     = models.CharField(max_length=100)
    intro     = models.TextField(blank=True)
    status    = models.CharField(max_length=16)  # draft publisher
    created   = models.DateTimeField(default=timezone.now())
    updated   = models.DateTimeField(auto_now=True)
    # is_delete = models.IntegerField()

    class Meta:
        ordering = ("-created",)
        db_table = 'wr_article'

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    article   = models.ForeignKey(Article, related_name='posts')
    version   = models.CharField(max_length=16)
    body      = models.TextField(blank=True)
    comments  = models.TextField(blank=True)
    status    = models.CharField(max_length=16)
    created   = models.DateTimeField(default=timezone.now())
    updated   = models.DateTimeField(auto_now=True)
    # is_delete = models.IntegerField()

    class Meta:
        ordering = ("-created",)
        db_table = 'wr_article_post'

    def __str__(self):
        return 'body of {0} [{1}]'.format(self.article, self.version)


class ArticleComment(models.Model):
    user         = models.ForeignKey(User, related_name='article_comments')
    article      = models.ForeignKey(Article, related_name='comments')
    article_post = models.ForeignKey(ArticlePost, related_name='article_post_comments')
    line_number  = models.IntegerField()
    body         = models.TextField(blank=True)
    created      = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created",)
        db_table = 'wr_article_comment'

    def __str__(self):
        return 'comment by {0} on {1}'.format(self.user, self.article)

article/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Article, ArticlePost, ArticleComment

# class ArticleForm(forms.ModelForm):
#     class Meta:
#         model = ArticlePost
#         fields = ('title')

article/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.models import User
from django.db.models import Count
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect

import json
from .models import Article, ArticlePost, ArticleComment
import pdb


@login_required
def article_list(request):
    articles_list = request.user.review_articles.filter(status="publisher")

    return render(request, "article/list.html", {
        "articles": articles_list,
    })

@login_required
def my_article_list(request):
    articles_list = request.user.article.all()

    return render(request, "article/my_list.html", {
        "articles": articles_list,
    })

@login_required
def article_post_list(request, id):
    article = get_object_or_404(Article, id=id)
    article_post_list = article.posts.all()

    return render(request, "article/post_list.html", {
        "article": article,
        "article_posts": article_post_list,
    })

@login_required
def article_create(request):
    if request.method == 'POST':
        try:
            article        = Article()
            article.author = request.user
            article.title  = request.POST['title']
            article.intro  = request.POST['intro']
            article.status = request.POST['status']
            article.save()

            article_post         = ArticlePost()
            article_post.article = article
            article_post.version = 'version-1'
            article_post.body    = request.POST['body']
            article_post.status  = request.POST['status']
            article_post.save()

            return HttpResponse(json.dumps({
                "status": "success",
                "url": reverse('article:article_post_list', kwargs={'id': article.id}),
            }), content_type="application/json")
        except:
            return HttpResponse(json.dumps({
                "status": "fail",
            }), content_type="application/json")

    return render(request, "article/create.html", {

    })


def article_comment(request, id):
    article = get_object_or_404(Article, id=id)
    if (request.user != article.author) and (not request.user in article.reviewers.all()):
        return HttpResponseRedirect(reverse('article:article_list'))

    pub_article_posts = article.posts.filter(status="publisher")
    if not pub_article_posts:
        return HttpResponseRedirect(reverse('article:article_list'))

    return render(request, "article/show.html", {
        'article': article,
        'pub_article_posts': pub_article_posts,
    })


@login_required
@csrf_exempt
def article_post_comment(request, id, vid):
    line = request.GET['line'];
    if not line:
        return HttpResponse()

    article = get_object_or_404(Article, id=id)
    article_post = get_object_or_404(ArticlePost, id=vid, article=article)
    article_comments = article_post.article_post_comments.filter(line_number=line)

    if request.method == 'POST':
        article_comment              = ArticleComment()
        article_comment.user         = request.user
        article_comment.article      = article
        article_comment.article_post = article_post
        article_comment.line_number = line
        article_comment.body = request.POST['body']
        article_comment.save()
        {"9": {"total": 3}, "11": {"total": 4}}

        comments = json.loads(article_post.comments) if article_post.comments else {}
        total = {'total': len(article_comments)}
        if line in comments:
            comments[line].update(total)
        else:
            comments[line] = total

        article_post.comments = json.dumps(comments)
        article_post.save()

        return HttpResponse(json.dumps({
            "status": "success",
        }), content_type="application/json")


    return render(request, "article/comment.html", {
        'line': line,
        'article': article,
        'article_post': article_post,
        'article_comments': article_comments,
    })

@login_required
def article_comment_list(request, id, vid):
    line = request.GET['line'];
    if not line:
        return HttpResponse()

    article = get_object_or_404(Article, id=id)
    article_post = get_object_or_404(ArticlePost, id=vid, article=article)
    article_comments = article_post.article_post_comments.filter(line_number=line)

    return render(request, "article/comment_show.html", {
        'line': line,
        'article': article,
        'article_post': article_post,
        'article_comments': article_comments,
    })


@login_required
@csrf_exempt
def article_edit(request, id, vid):
    if request.method == 'POST':
        try:
            article = request.user.article.get(id=id)
            article.title  = request.POST['title']
            article.intro  = request.POST['intro']
            if article.status == 'draft':
                article.status = request.POST['status']

            article.save()

            article_post = article.posts.get(id=vid)
            if article_post.status == 'publisher':
                raise ValueError

            article_post.body   = request.POST['body']
            article_post.status = request.POST['status']
            article_post.save()

            return HttpResponse(json.dumps({
                "status": "success",
                "url": reverse('article:article_post_list', kwargs={'id': article.id}),
            }), content_type="application/json")
        except:
            return HttpResponse(json.dumps({
                "status": "fail",
            }), content_type="application/json")

    article = get_object_or_404(Article, id=id)
    article_post = get_object_or_404(ArticlePost, id=vid, article=article)
    if article_post.status == 'publisher':
        return HttpResponseRedirect(reverse('article:article_post_list', kwargs={'id': article.id}))

    pub_article_posts = article.posts.filter(status="publisher")

    return render(request, "article/edit.html", {
        'article': article,
        'article_post': article_post,
        'pub_article_posts': pub_article_posts,
    })

@login_required
@csrf_exempt
def article_reedit(request, id, vid):
    if request.method == 'POST':
        try:
            article = request.user.article.get(id=id)
            article.title  = request.POST['title']
            article.intro  = request.POST['intro']
            if article.status == 'draft':
                article.status = request.POST['status']
            article.save()

            article_post         = ArticlePost()
            article_post.article = article

            post_count = article.posts.count() + 1
            article_post.version = 'version-' + str(post_count)

            article_post.body   = request.POST['body']
            article_post.status = request.POST['status']
            article_post.save()

            return HttpResponse(json.dumps({
                "status": "success",
                "url": reverse('article:article_post_list', kwargs={'id': article.id}),
            }), content_type="application/json")
        except:
            return HttpResponse(json.dumps({
                "status": "fail",
            }), content_type="application/json")
        
    article = get_object_or_404(Article, id=id)
    article_post = get_object_or_404(ArticlePost, id=vid, article=article)

    pub_article_posts = article.posts.filter(status="publisher")

    return render(request, "article/reedit.html", {
        'article': article,
        'article_post': article_post,
        'pub_article_posts': pub_article_posts,
    })

@login_required
def article_post_body(request, id):
    try:
        vid = request.GET['vid'];

        article      = Article.objects.get(id=id)
        article_post = article.posts.get(id=vid)

        return HttpResponse(json.dumps({
            "status": "success",
            "body": article_post.body,
            "comments": json.loads(article_post.comments) if article_post.comments else {},
            "post_comment_url": reverse('article:article_post_comment', kwargs={'id': article.id, 'vid': article_post.id})
        }), content_type="application/json")
    except:
        return HttpResponse(json.dumps({
            "status": "fail",
        }), content_type="application/json")

article/templates/article/comment.html
<div style="padding:10px;">
  <div class="mb1">当前行：<span class="text-danger">{{ line }}</span></div>
  <div class="input-group">
    <input class="form-control" placeholder="批注...">
    <span class="input-group-btn"><button class="btn btn-default btn-comment-post" type="button" data-url="{% url 'article:article_post_comment' article.id article_post.id %}?line={{ line }}">提交</button></span>
  </div>
  {% for comment in article_comments %}
    <div class="media" style="padding-left: 15px;">
      <div class="media-body">
        <div class="pull-right"></div>
        <div class="">{{ comment.body|linebreaksbr }}</div>
        <div class="text-muted">{{ comment.user }}&nbsp;&nbsp;{{ comment.created|date:"Y-m-d H:i:s" }}</div>
      </div>
    </div>
  {% empty %}
    <div class="media text-muted"><div class="media-body">暂无批注</div></div>
  {% endfor %}
</div>

article/templates/article/comment_show.html
<div style="padding:10px;">
  <div class="mb1">当前行：<span class="text-danger">{{ line }}</span></div>
  {% for comment in article_comments %}
    <div class="media" style="padding-left: 15px;">
      <div class="media-body">
        <div class="pull-right"></div>
        <div class="">{{ comment.body|linebreaksbr }}</div>
        <div class="text-muted">{{ comment.user }}&nbsp;&nbsp;{{ comment.created|date:"Y-m-d H:i:s" }}</div>
      </div>
    </div>
  {% empty %}
    <div class="media text-muted"><div class="media-body">暂无批注</div></div>
  {% endfor %}
</div>

article/templates/article/create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章发布{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'libs/editor-md/css/editormd.min.css' %}">
<link rel="stylesheet" href="{% static 'article/css/show.css' %}">
{% endblock %}

{% block full_content %}
<div class="articel-save-container">

  <form class="form" id="form-article-post" action="{% url 'article:article_create' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <h2>文章添加</h2>
      <hr>
    </div>

    <div class="form-group">
      <label for="id_title">标题</label>
      <input type="text" id="id_title" class="form-control" placeholder="标题" name="title">
    </div>

    <div class="form-group">
      <label for="id_intro">简介</label>
      <textarea name="intro" id="id_intro" class="form-control minimum" placeholder="简介"></textarea> 
    </div>

    <div class="form-group">
      <label for="id_body">内容</label>
      <div id="editormd">
        <textarea class="form-control hide" id="id_body" name="body"></textarea>
      </div>
    </div>

    <div class="form-group">
      <a class="btn btn-default btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="draft">保存</a>
      <a class="btn btn-success btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="publisher">保存并发布</a>
    </div>

  </form>
</div>
{% endblock %}

{% block script %}
<script src="{% static 'libs/editor-md/editormd.min.js' %}"></script>
<script src="{% static 'article/js/create.js' %}"></script>
{% endblock %}

article/templates/article/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章编辑{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'libs/editor-md/css/editormd.min.css' %}">
<link rel="stylesheet" href="{% static 'article/css/show.css' %}">
{% endblock %}

{% block full_content %}
<div class="articel-save-container">

  <form class="form" id="form-article-post" action="{% url 'article:article_edit' article.id article_post.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <h2>文章编辑</h2>
      <hr>
    </div>

    <div class="form-group">
      <label for="id_title">标题</label>
      <input type="text" id="id_title" class="form-control" placeholder="标题" name="title" value="{{ article.title }}">
    </div>

    <div class="form-group">
      <label for="id_intro">简介</label>
      <textarea name="intro" id="id_intro" class="form-control minimum" placeholder="简介">{{ article.title }}</textarea> 
    </div>

    <div class="form-group">
      <label for="id_body">内容</label>
      {% if  pub_article_posts %}
      <div class="editormd-warp row">
        <div class="col-sm-4">
          <div class="version-choice">
            <select class="form-control change-version" data-url="{% url 'article:article_post_body' article.id %}">
              {% for post in pub_article_posts %}
                <option {% if post.id == article_post.id %}selected="selected"{% endif %} value="{{ post.id }}">{{ post.version }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="markdown-comment-wrap reedit-warp">
            <div class="markdown-show-wrap">
              <div class="markdown-comment-gutters"></div>
              <div id='editormd-view' class="markdown-show markdown-comment-show"></div>
            </div>
          </div>

        </div>
        <div class="col-sm-8">
          <div id="editormd">
            <textarea class="form-control hide" id="id_body" name="body">{{ article_post.body }}</textarea>
          </div>
        </div>
      </div>
      {% else %}
        <div id="editormd">
          <textarea class="form-control hide" id="id_body" name="body">{{ article_post.body }}</textarea>
        </div>
      {% endif %}
    </div>

    <div class="form-group">
      <hr>
      <a class="btn btn-default btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="draft">保存</a>
      <a class="btn btn-success btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="publisher">保存并发布</a>
    </div>

  </form>
</div>
{% endblock %}

{% block script %}
<script src='{% static "libs/editor-md/lib/marked.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/prettify.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/raphael.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/underscore.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/flowchart.min.js" %}''></script>
<script src='{% static "libs/editor-md/lib/jquery.flowchart.min.js" %}'></script>
<script src="{% static 'libs/editor-md/editormd.min.js' %}"></script>
<script src="{% static 'article/js/edit.js' %}"></script>
{% endblock %}

article/templates/article/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}

{% block content %}

  <div class="">
    <h2>文章列表</h2>
  </div>

  <table class="table">
    <tr>
      <th>序号</th>
      <th width="50%">标题</th>
      <th>作者</th>
      <th>操作</th>
    </tr>
    {% for article in articles %}
      <tr>
        <th>{{ forloop.counter }}</th>
        <td><a href="{% url 'article:article_comment' article.id %}">{{ article.title }}</a></td>
        <td>{{ article.author }}</td>
        <td>
          <div class="btn-group btn-group-sm" role="group">
            <a class="btn btn-default" href="{% url 'article:article_comment' article.id %}">查看</a>
          </div>
        </td>
      </tr>
    {% empty %}
      <tr><td class="text-center" colspan="3">暂无文章。</td></tr>
    {% endfor %}
  </table>

{% endblock %}

{% block script %}

{% endblock %}

article/templates/article/my_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}

{% block content %}

  <div class="">
    <a href="{% url 'article:article_create' %}" class="btn btn-sm btn-success pull-right">添加文章</a>
    <h2>文章列表</h2>
  </div>

  <table class="table">
    <tr>
      <th>序号</th>
      <th width="50%">标题</th>
      <th>操作</th>
    </tr>
    {% for article in articles %}
      <tr>
        <th>{{ forloop.counter }}</th>
        {% if article.status == 'publisher' %}
          <td><a href="{% url 'article:article_comment' article.id %}">{{ article.title }}</a></td>
        {% else %}
          <td>{{ article.title }}</td>
        {% endif %}
        <td>
          <div class="btn-group btn-group-sm" role="group">
            <a class="btn btn-default btn-category-edit" href="{% url 'article:article_post_list' article.id %}">详情</a>
          </div>
        </td>
      </tr>
    {% empty %}
      <tr><td class="text-center" colspan="3">还没有发布文章，太懒了。</td></tr>
    {% endfor %}
  </table>

{% endblock %}

{% block script %}

{% endblock %}

article/templates/article/post_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章列表{% endblock %}

{% block content %}

  <h2>{{ article.title }}</h2>

  <table class="table">
    <tr>
      <th>序号</th>
      <th>版本</th>
      <th>状态</th>
      <th>操作</th>
    </tr>
    {% for post in article_posts %}
      <tr>
        <th>{{ forloop.counter }}</th>
        <td>{{ post.version }}</td>
        <td>{% if post.status == 'publisher' %}已发布{% elif post.status == 'draft' %}草稿{% endif %}</td>
        <td>
          <div class="btn-group btn-group-sm" role="group">
            {% if post.status == 'publisher' %}
              <a class="btn btn-default btn-category-edit" href="{% url 'article:article_reedit' article.id post.id %}">重新编辑</a>
            {% elif post.status == 'draft' %}
              <a class="btn btn-default btn-category-edit" href="{% url 'article:article_edit' article.id post.id %}">编辑</a>
            {% endif %}
          </div>
        </td>
      </tr>
    {% empty %}
      <tr><td class="text-center" colspan="3">还没有发布文章，太懒了。</td></tr>
    {% endfor %}
  </table>

{% endblock %}

{% block script %}

{% endblock %}

article/templates/article/reedit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章重新编辑{% endblock %}
{% block style %}
<link rel="stylesheet" href="{% static 'libs/editor-md/css/editormd.min.css' %}">
<link rel="stylesheet" href="{% static 'article/css/show.css' %}">
{% endblock %}

{% block full_content %}
<div class="articel-save-container">

  <form class="form" id="form-article-post" action="{% url 'article:article_reedit' article.id article_post.id %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <h2>文章重新编辑</h2>
      <hr>
    </div>

    <div class="form-group">
      <label for="id_title">标题</label>
      <input type="text" id="id_title" class="form-control" placeholder="标题" name="title" value="{{ article.title }}">
    </div>

    <div class="form-group">
      <label for="id_intro">简介</label>
      <textarea name="intro" id="id_intro" class="form-control minimum" placeholder="简介">{{ article.title }}</textarea> 
    </div>

    <div class="form-group">
      <label for="id_body">内容</label>
      <div class="editormd-warp row">
        <div class="col-sm-4">

          <div class="version-choice">
            <select class="form-control change-version" data-url="{% url 'article:article_post_body' article.id %}">
              {% for post in pub_article_posts %}
                <option {% if post.id == article_post.id %}selected="selected"{% endif %} value="{{ post.id }}">{{ post.version }}</option>
              {% endfor %}
            </select>
          </div>

          <div class="markdown-comment-wrap reedit-warp">
            <div class="markdown-show-wrap">
              <div class="markdown-comment-gutters"></div>
              <div id='editormd-view' class="markdown-show markdown-comment-show"></div>
            </div>
          </div>

        </div>
        <div class="col-sm-8">

          <div id="editormd">
            <textarea class="form-control hide" id="id_body" name="body">{{ article_post.body }}</textarea>
          </div>

        </div>
      </div>
    </div>

    <div class="form-group">
      <hr>
      <a class="btn btn-default btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="draft">保存</a>
      <a class="btn btn-success btn-article-save" href="javascript:;" data-target="#form-article-post" data-status="publisher">保存并发布</a>
    </div>

  </form>


</div>
{% endblock %}

{% block script %}
<script src='{% static "libs/editor-md/lib/marked.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/prettify.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/raphael.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/underscore.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/flowchart.min.js" %}''></script>
<script src='{% static "libs/editor-md/lib/jquery.flowchart.min.js" %}'></script>
<script src="{% static 'libs/editor-md/editormd.min.js' %}"></script>
<script src="{% static 'article/js/reedit.js' %}"></script>
{% endblock %}

article/templates/article/show.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}文章详情{% endblock %}
{% block style %}
<link href="http://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="{% static 'libs/editor-md/css/editormd.min.css' %}">
<link rel="stylesheet" href="{% static 'article/css/show.css' %}">
{% endblock %}

{% block content %}

  <h1 class="text-left">{{ article.title }}</h1>
  <p class="text-left">{{ article.author }}</p>
  <p class="text-left">{{ article.created }}</p>

  <form class="form-inline">
    <div class="form-group">
      <label for="exampleInputName2">版本：</label>
      <select class="form-control change-version" data-url="{% url 'article:article_post_body' article.id %}">
        {% for post in pub_article_posts %}
          <option value="{{ post.id }}">{{ post.version }}</option>
        {% endfor %}
      </select>
    </div>
  </form>

  <div class="markdown-comment-wrap">
    <div class="markdown-show-wrap">
      <div id='editormd-view' class="markdown-show markdown-comment-show"></div>
      <div class="markdown-comment-gutters"></div>
    </div>
  </div>

{% endblock %}

{% block script %}
<script src='{% static "libs/editor-md/lib/marked.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/prettify.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/raphael.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/underscore.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/sequence-diagram.min.js" %}'></script>
<script src='{% static "libs/editor-md/lib/flowchart.min.js" %}''></script>
<script src='{% static "libs/editor-md/lib/jquery.flowchart.min.js" %}'></script>
<script src="{% static 'libs/editor-md/editormd.min.js' %}"></script>
<script src="{% static 'article/js/show.js' %}"></script>
{% endblock %}