account/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^login/$', auth_views.login, {"template_name": "account/login.html", "redirect_authenticated_user": True}, name='login'),
    url(r'^logout/$', auth_views.logout, {"template_name": "account/logout.html"}, name='logout'),
]

article/urls.py
from django.conf.urls import url
from django.conf import settings
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    url(r'^list$', views.article_list, name='article_list'),
    url(r'^my/list$', views.my_article_list, name='my_article_list'),
    url(r'^(?P<id>\d+)/post/list$', views.article_post_list, name='article_post_list'),
    url(r'^create$', views.article_create, name='article_create'),
    url(r'^(?P<id>\d+)/comment$', views.article_comment, name='article_comment'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/comment$', views.article_post_comment, name='article_post_comment'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/edit$', views.article_edit, name='article_edit'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/reedit$', views.article_reedit, name='article_reedit'),
    url(r'^(?P<id>\d+)/body$', views.article_post_body, name='article_post_body'),
    url(r'^(?P<id>\d+)/v/(?P<vid>\d+)/comment/list$', views.article_comment_list, name='article_comment_list'),

]

project/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from account import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls', namespace='account', app_name='account')),
    url(r'^article/', include('article.urls', namespace='article', app_name='article')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler400 = 'project.views.handler400'
handler403 = 'project.views.handler403'
handler404 = 'project.views.handler404'
handler500 = 'project.views.handler500'

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.bootcss.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{% static 'common/css/main.css' %}" rel="stylesheet">
    {% block style %}{% endblock %}

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    {% include 'header.html' %}
    {% block full_content %}
      <div class="container">
        {% block content %}{% endblock %}
      </div>
    {% endblock %}
    {% include 'footer.html' %}
    {% block script %}{% endblock %}
  </body>
</html>

templates/footer.html
{% load staticfiles %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

<script src="//cdn.bootcss.com/layer/3.0.1/layer.min.js"></script>

templates/header.html
{% load staticfiles %}

<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'home' %}">首页</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'article:article_list' %}">全部文章</a></li>
        <li><a href="{% url 'article:my_article_list' %}">我的文章</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }} <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="{% url 'account:logout' %}"><i class="fa fa-sign-out fa-fw"></i>安全退出</a></li>
            </ul>
          </li>
        {% else %}
          <li><a href="{% url 'account:login' %}">登录</a></li>
        {% endif %}
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>